version: "3.4"
services:
  master:
    hostname: master
    image: jkhlr/pytorch-mpi
    ports:
      - 127.0.0.1:22:22
    networks:
      - net
    volumes:
      - ./src:/home/pi/src
  slave1:
    hostname: slave1
    image: jkhlr/pytorch-mpi
    networks:
      - net
    volumes:
      - ./src:/home/pi/src
  slave2:
      hostname: slave2
      image: jkhlr/pytorch-mpi
      networks:
        - net
      volumes:
        - ./src:/home/pi/src

networks:
  net:
    driver: bridge
