version: "3.4"
services:
  master:
    hostname: master
    image: jkhlr/pytorch-mpi
    ports:
      - 127.0.0.1:22:22
    networks:
      - net
    volumes:
      - .:/home/pi/remote_repo
  slave1:
    hostname: slave1
    image: jkhlr/pytorch-mpi
    networks:
      - net
    volumes:
      - .:/home/pi/remote_repo
  slave2:
    hostname: slave2
    image: jkhlr/pytorch-mpi
    networks:
      - net
    volumes:
      - .:/home/pi/remote_repo
  slave3:
    hostname: slave3
    image: jkhlr/pytorch-mpi
    networks:
      - net
    volumes:
      - .:/home/pi/remote_repo
networks:
  net:
    driver: bridge
